apiVersion: apps/v1
kind: Deployment
metadata:
  name: npm-app
spec:
  selector:
    matchLabels:
      app: npm-app
  template:
    metadata:
      labels:
        app: npm-app
    spec:
      containers:
        - name: npm-app
          image: imageName # IMPORTANT: Update!
          imagePullPolicy: Always
          ports:
            - containerPort: 443
              name: https
            - containerPort: 80
              name: http
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: npm-app
  name: npm-app
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      protocol: TCP
    - name: http
      port: 80
      protocol: TCP
  selector:
    app: npm-app
